package(default_visibility = ["//visibility:public"])

exports_files([
    "main.css",
    "main.js"
])

# load("@build_bazel_rules_nodejs//:defs.bzl", "rollup_bundle")
#
# rollup_bundle(
#     name = "bundle",
#     srcs = glob(["*.js"]),
#     entry_point = "main.js",
# )
